### ISSUE TITLE
more benchmark for interpolation

### ISSUE THREAD

**Issue by duhd1993** [pierre-haessig/stodynprog#2]
Thanks for keeping this cython implementation. FYI, I just find the github account of dolo, has  a separate repo for an interpolation tool. It's not implemented with cython but with numba. Maybe you can give it a try.

https://github.com/EconForge/interpolation.py

**Comment by pierre-haessig** [comment]
Thanks for the reference. Indeed, I had noticed that @albop and his colleagues moved forward using Numba. Also, their `interpolation.py` package provides more interpolation methods than just multilinear (e.g. splines).

For the moment, the old Cython-based solution I kept is working well enough and I find it a bit reassuring to have something statically compiled. Also I don't need smoother interpolation methods because I have several problems with piecewise linear function (i.e. with discontinuities in the derivative).
